---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: recolector
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: recolector
    spec:
      containers:
      - name: recolector
        image: ademord/recolector
        ports:
        - containerPort: 55551
          protocol: TCP
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
