---
kind: Service
apiVersion: v1
metadata:
  name: recolector
  namespace: default
  creationTimestamp: 
  labels:
    service: recolector
spec:
  ports:
  - name: '55551'
    protocol: TCP
    port: 80
    targetPort: 55551
  selector:
    service: recolector
  type: LoadBalancer
status:
  loadBalancer: {}
