---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /share
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi