apiVersion: v1
kind: Pod
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  containers:
    - image: {{ .Values.image }}
      name: {{ .Chart.Name }}
      env:
      - name: VIDEO_NAME
        value:  {{ .Values.env.VIDEO_NAME }}
      - name: IP
        value: {{ .Values.env.IP }}
      - name: TARGET_SERVICE
        value: {{ .Values.env.TARGET_SERVICE }}
      ports: 
      - containerPort: 55551
        protocol: TCP
      resources: {}
  restartPolicy: Never
