---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: coincidencias
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: coincidencias
    spec:
      containers:
      - name: coincidencias
        image: ademord/coincidencia
        ports:
        - containerPort: 55555
          protocol: TCP
        env:
        - name: DATABASE_HOST
          value: homestead
        - name: DATABASE_PORT
          value: '5432'
        volumeMounts:
        - mountPath: "/media"
          name: media
      volumes:
      - name: media
        hostPath:
          path: "/share"