apiVersion: v1
kind: Service
metadata: 
  creationTimestamp: null
  labels: 
    service: reconocedor
  name: reconocedor
  namespace: panchito
spec: 
  ports: 
    - name: "5000"
      port: 80
      protocol: TCP
      targetPort: 5000
  selector: 
    service: reconocedor
  type: LoadBalancer
status: 
  loadBalancer: {}
