---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: homestead
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: homestead
    spec:
      containers:
      - name: homestead
        image: ademord/homestead:latest
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
