apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  creationTimestamp: null
  name: reconocedor
  namespace: panchito
spec: 
  replicas: 1
  strategy: {}
  template: 
    metadata: 
      creationTimestamp: ~
      labels: 
        service: reconocedor
    spec: 
      containers: 
        - image: "ademord/reconocedor:latest"
          name: reconocedor
          ports: 
            - containerPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
