---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: lugares
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: lugares
    spec:
      containers:
      - name: lugares
        image: ademord/lugar:latest
        ports:
        - containerPort: 55550
          protocol: TCP
        env:
        - name: DATABASE_HOST
          value: homestead
        - name: DATABASE_PORT
          value: '5432'
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
