---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: camaras
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: camaras
    spec:
      containers:
      - name: camaras
        image: ademord/camara:latest
        ports:
        - containerPort: 55551
          protocol: TCP
        env:
        - name: DATABASE_HOST
          value: homestead
        - name: DATABASE_PORT
          value: '5432'
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
