---
kind: Service
apiVersion: v1
metadata:
  name: propietarios
  namespace: default
  creationTimestamp: 
  labels:
    service: propietarios
spec:
  ports:
  - name: '55555'
    protocol: TCP
    port: 80
    targetPort: 55555
  selector:
    service: propietarios
status:
  loadBalancer: {}
