---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: recolector-listener
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: recolector-listener
    spec:
      containers:
      - name: recolector-listener
        image: ademord/listener
        ports:
        - containerPort: 55555
          protocol: TCP
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: recolector-listener
  namespace: default
  creationTimestamp: 
  labels:
    service: recolector-listener
spec:
  ports:
  - name: '55555'
    protocol: TCP
    port: 80
    targetPort: 55555
  selector:
    service: recolector-listener
  type: NodePort
status:
  loadBalancer: {}
