---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis-adder
  namespace: default
  creationTimestamp: 
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: redis-adder
    spec:
      containers:
      - name: redis-adder
        image: ademord/redis-adder
        ports:
        - containerPort: 55555
          protocol: TCP
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
